### PR TITLE
Coobook fix

### LINKED ISSUE #75: Cancelled new cookbooks don't disappear
### What happens
If you add a new cookbook, and then try cancel that cookbook, it still appears in the list

### What should happen
Cancelling a new cookbook should not add it to the list

### Suggestion

New cookbooks get added to the database immediately and then they just get edited, so when a new cookbook is added and then cancelled, the cancel button should then delete the newly created cookbook

### PR DESCRIPTION
**Pull request by Smithash**
Fixed the issue of cancelling the adding of a new cookbook 
Commented out the delete from the actual cookbook -> there are issue after you delete. If u still want it in there, i will fix it. otherwise i dont think its necessary with the delete on the collections page.

fixes #75

### CODE REVIEW

**Review by lisaa-g — APPROVED** [review]

File: src/routes/(app)/collections/cookbooks/+page.svelte [hunk 1]
```diff
@@ -85,9 +85,16 @@
...
 							><Save /></button>
 						<button
-							on:click={() => {
+							on:click={async () => {
 								currentCookbook = uneditedCookbook;
 								editCookbook = false;
+								const index = cookbooks.indexOf(currentCookbook);
+								cookbooks.splice(index, 1);
+
+								await fetch('/api/cookbook', {
```
Comment (orwellian225) [inline src/routes/(app)/collections/cookbooks/+page.svelte:94]: This is not going to work. What happens if a user just wants to edit a cookbook, and then they cancel the edit? It will delete the whole cookbook even though that is not what they wanted to do

**Review by orwellian225 — CHANGES_REQUESTED** [review]

File: src/routes/(app)/collections/cookbooks/+page.svelte [hunk 2]
```diff
@@ -85,7 +87,19 @@
 							class="items-center justify-center flex flex-row rounded-lg border-2 border-emerald-500 dark:bg-emerald-700 bg-emerald-100 p-1 dark:hover:bg-emerald-800 hover:bg-emerald-300"
 							><Save /></button>
 						<button
-							on:click={() => {
+							on:click={async () => {
+								// console.log(uneditedCookbook);
+								// currentCookbook = uneditedCookbook;
+								console.log(newCookbook);
```
Comment (orwellian225) [inline src/routes/(app)/collections/cookbooks/+page.svelte:93]: Pls remove

**Review by orwellian225 — CHANGES_REQUESTED** [review]

**Review by orwellian225 — APPROVED** [review]
